name: elta
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - astor==0.8.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - cycler==0.12.1
      - dnspython==2.7.0
      - einops==0.4.1
      - filelock==3.13.1
      - fsspec==2024.6.1
      - future==1.0.0
      - huggingface-hub==0.30.2
      - hyperopt==0.1.2
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - json-tricks==3.17.3
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.3.4
      - mpmath==1.3.0
      - networkx==3.3
      - nni==2.6.1
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.0.0
      - prettytable==3.16.0
      - psutil==7.0.0
      - pymongo==4.12.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pythonwebhdfs==0.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - responses==0.25.7
      - safetensors==0.5.3
      - schema==0.7.7
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - simplejson==3.20.1
      - six==1.17.0
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - timm==0.6.12
      - tqdm==4.67.1
      - triton==3.3.0
      - typeguard==4.4.2
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - websockets==15.0.1
prefix: /home/cyx/miniconda3/envs/elta
